POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmluaGFyYWlvbGFzZXIiLCJpZCI6IjYyZDg0ZDRhZTlhMjc3YThjNTRmZTBhZSIsImlhdCI6MTY1ODM0NzgxNH0.oVxoB10GLX6OAPlsjsSBIQ_uRZN14vRRnJuNKv5khP0

{
    "title": "sample",
    "author": "Wed, 21 Oct 2015 18:27:50 GMT",
    "url": "some http:// url",
    "likes": 5
}